version: '3.8'

services:
  react-app:
    build: .
    container_name: react-app-container
    ports:
      - "5173:5173" # Exposing port 5173
    volumes:
      - .:/app
      - /app/node_modules # Persist node_modules folder inside container
    environment:
      - CHOKIDAR_USEPOLLING=true # For enabling file change detection in Docker
    command: npm run dev
