version: '3.8'

services:
  api:
    build: ./auth-service-be
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/auth-app
      - JWT_SECRET=your-secure-secret-key
    depends_on:
      - mongodb
    volumes:
      - ./auth-service-be:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  react-app:
    build: ./auth-service-fe
    container_name: react-app-container
    ports:
      - "5173:5173"
    volumes:
      - ./auth-service-fe:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev

volumes:
  mongodb_data:
