version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/auth-app
      - JWT_SECRET=your-secure-secret-key
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app           
      - /usr/src/app/node_modules 
    command: npm run start:dev

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
